"""intial work

Revision ID: 010828742b7e
Revises: 
Create Date: 2022-02-07 12:45:52.009629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010828742b7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coupons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Coupons')
    # ### end Alembic commands ###
